d = {}
name = input("Enter Friends name: ")
lang = input("Enter your language: ")
d.update({name : lang})
name = input("Enter Friends name: ")
lang = input("Enter your language: ")
d.update({name : lang})
name = input("Enter Friends name: ")
lang = input("Enter your language: ")
d.update({name : lang})
name = input("Enter Friends name: ")
lang = input("Enter your language: ")
d.update({name : lang})
print(d)